replicaCount: 2
image:
  repository: ghcr.io/bmiazek18/facebook-clone-frontend
  tag: "707887b83da3819a68d4ba7c42ec70811f724749"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
ingress:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 384Mi
keycloakUrl: "https://auth.lab-bm.com"
frontendUrl: "https://lab-bm.com"
apiUrl: "https://api.lab-bm.com"
mqttUrl: "ws://localhost:8080/mqtt"
