replicaCount: 2

image:
  repository: ghcr.io/bmiazek18/facebook-clone1-frontend
  tag: "91810f39278380259842b0b9beb8705ed3deac75"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 384Mi

keycloakUrl: "https://auth.lab-bm.com"
frontendUrl: "https://lab-bm.com"
apiUrl: "https://api.lab-bm.com"
mqttUrl: "ws://localhost:8080/mqtt"