replicaCount: 2
image:
  repository: ghcr.io/bmiazek18/facebook-clone-frontend
  tag: "4c72c50408c1d76f766394fba93c4bace6b18ffd"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
ingress:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 384Mi
keycloakUrl: "https://auth.lab-bm.com"
keycloak:
  publicUrl: "https://auth.lab-bm.com"
  internalUrl: "http://keycloak-service.apps.svc.cluster.local:8080"
frontendUrl: "https://lab-bm.com"
apiUrl: "https://api.lab-bm.com"
mqttUrl: "ws://localhost:8080/mqtt"
redis:
  host: "redis.apps.svc.cluster.local"
  port: "6379"
  url: "redis://redis.apps.svc.cluster.local:6379"
apiGatewayUrl: "http://api-gateway.apps.svc.cluster.local:8080"
tusdUrl: "http://api-gateway.apps.svc.cluster.local:8080"
