apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: keycloak
  namespace: {{ .Release.Namespace | default "apps" }}
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image }}
          args:
            - "start-dev"
            - "--spi-action-token-handler-action-token-example-enabled=true"
            - "--spi-action-token-handler-action-token-example-hmac-secret={{ .Values.keycloak.actionTokenSecret }}"
          env:
            # Baza danych
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://postgres-keycloak:5432/{{ .Values.database.name }}"
            - name: KC_DB_USERNAME
              value: {{ .Values.database.user | quote }}
            - name: KC_DB_PASSWORD
              value: {{ .Values.database.password | quote }}

            # Domena i integracja z Cloudflare SSL
            - name: KC_HOSTNAME
              value: {{ .Values.keycloak.hostname | quote }}
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_HEALTH_ENABLED
              value: "true"

            # Dane konta administratora
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: {{ .Values.keycloak.adminUser | quote }}
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: {{ .Values.keycloak.adminPassword | quote }}
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.adminUser | quote }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.keycloak.adminPassword | quote }}

            # Konfiguracja logów
            - name: KC_LOG_LEVEL
              value: "INFO,org.keycloak.cookie:ERROR"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15
            failureThreshold: 3