apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: mailpit
  namespace: {{ .Release.Namespace | default "apps" }}
  labels:
    app: mailpit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: {{ .Values.mailpit.image }}
          ports:
            - name: smtp
              containerPort: 1025
            - name: ui
              containerPort: 8025