keycloak:
  hostname: "auth.lab-bm.com"
  image: "ghcr.io/bmiazek18/facebook-clone-keycloak:548524b9cb9a1cad2e17dddfed5441c32493f044"
  adminUser: "admin"
  adminPassword: "admin"
  actionTokenSecret: "7bA9xN2mK5vP8rQ1wZ4eT7yU0iO3pL6k"
  replicaCount: 1
  servicePort: 8080
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"
database:
  image: "postgres:16-alpine"
  name: "keycloak"
  user: "keycloak"
  password: "keycloak"
  storageSize: "5Gi"
  servicePort: 5432
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
mailpit:
  enabled: true
  image: "axllent/mailpit:latest"
  smtpPort: 1025
  uiPort: 8025
image:
  repository: ghcr.io/bmiazek18/facebook-clone-keycloak
  tag: b4dd7e8bb4a79ecfe8186a16d9bb6ec7cdd42897
