apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: nuxt-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: NUXT_PUBLIC_KEYCLOAK_URL
              value: {{ .Values.keycloakUrl | quote }}
            - name: NUXT_PUBLIC_FRONTEND_URL
              value: {{ .Values.frontendUrl | quote }}
            - name: NUXT_PUBLIC_API_URL
              value: {{ .Values.apiUrl | quote }}
            - name: NUXT_PUBLIC_MQTT_URL
              value: {{ .Values.mqttUrl | quote }}
            - name: REDIS_HOST
              value: {{ .Values.redis.host | default "redis-master.apps.svc.cluster.local" | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | default "6379" | quote }}
            - name: REDIS_URL
              value: {{ .Values.redis.url | default "redis://redis-master.apps.svc.cluster.local:6379" | quote }}
            - name: NUXT_REDIS_HOST
              value: {{ .Values.redis.host | default "redis-master.apps.svc.cluster.local" | quote }}
            - name: NUXT_REDIS_PORT
              value: {{ .Values.redis.port | default "6379" | quote }}
            - name: NUXT_REDIS_URL
              value: {{ .Values.redis.url | default "redis://redis-master.apps.svc.cluster.local:6379" | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}