namespace: apps

grafana:
  adminUser: admin
  adminPassword: admin-password
  service:
    type: ClusterIP
    port: 3000

loki:
  persistence:
    size: 10Gi
  service:
    port: 3100

jaeger:
  service:
    queryPort: 16686
    otlpGrpcPort: 4317
    otlpHttpPort: 4318

prometheus:
  service:
    port: 9090
