apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: apollo-router-config
data:
  router.yaml: |
    supergraph:
      listen: 0.0.0.0:4000
      path: /graphql
      introspection: true
    cors:
      allow_any_origin: true
    sandbox:
      enabled: true
    homepage:
      enabled: false
    include_subgraph_errors:
      all: true
    health_check:
      listen: 0.0.0.0:8088
      path: /health
    headers:
      all:
        request:
          - propagate:
              named: "Authorization"
          - propagate:
              named: "X-User-Id"
          - propagate:
              named: "X-Actor-Id"
          - propagate:
              named: "X-Entity-Type"
          - propagate:
              named: "X-Original-User-Id"
    rhai:
      scripts: "/dist/config"
      main: "main.rhai"
  main.rhai: |
{{ .Files.Get "files/main.rhai" | indent 4 }}
