apiVersion: v1
kind: ConfigMap
metadata:
  name: apollo-router-config
data:
  router.yaml: |
    supergraph:
      listen: 0.0.0.0:4000
      introspection: true
    cors:
      allow_any_origin: true
    sandbox:
      enabled: true
    homepage:
      enabled: false
    include_subgraph_errors:
      all: true
    authentication:
      router:
        jwt:
          jwks:
            - url: {{ .Values.keycloakJwksUrl | quote }}
          header_name: Authorization
          header_value_prefix: Bearer
    headers:
      all:
        request:
          - propagate:
              named: "Authorization"
          - propagate:
              named: "X-User-Id"
          - propagate:
              named: "X-Actor-Id"
          - propagate:
              named: "X-Entity-Type"
          - propagate:
              named: "X-Original-User-Id"
    rhai:
      scripts: "/dist/config"
      main: "main.rhai"
  main.rhai: |
{{ .Files.Get "files/main.rhai" | indent 4 }}
