apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: keeper-analytics
  namespace: {{ .Release.Namespace | default "apps" }}
spec:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi

---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: clickhouse-analytics
  namespace: {{ .Release.Namespace | default "apps" }}
spec:
  replicas: 1
  shards: 1
  keeperClusterRef:
    name: keeper-analytics
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
