apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: mosquitto-config
  namespace: {{ .Release.Namespace | default "default" }}
data:
  mosquitto.conf: |
    persistence true
    persistence_location /var/lib/mosquitto/

    log_dest stdout

    # Main MQTT Listener
    listener 1883
    
    # Websocket Listener
    listener 9002
    protocol websockets

    allow_anonymous false

    # Auth Plugin Configuration (go-auth)
    plugin /mosquitto/go-auth.so
    auth_opt_check_prefix false
    auth_opt_backends http
    auth_opt_http_host userservice
    auth_opt_http_port 8081
    auth_opt_http_getuser_uri /internal/mqtt-auth/user
    auth_opt_http_aclcheck_uri /internal/mqtt-auth/acl
    auth_opt_http_superuser_uri /internal/mqtt-auth/superuser
    auth_opt_http_response_mode status
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: mqtt-broker
  namespace: {{ .Release.Namespace | default "apps" }}
  labels:
    app: mqtt-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      {{- if .Values.istio.enabled }}
      serviceAccountName: mqtt-broker-sa
      {{- end }}
      containers:
        - name: mosquitto
          image: iegomez/mosquitto-go-auth:latest
          ports:
            - name: mqtt
              containerPort: 1883
            - name: websockets
              containerPort: 9002
          volumeMounts:
            - name: config-volume
              mountPath: /etc/mosquitto/mosquitto.conf
              subPath: mosquitto.conf
            - name: config-volume
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: data-volume
              mountPath: /var/lib/mosquitto
      volumes:
        - name: config-volume
          configMap:
            name: mosquitto-config
        - name: data-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: mqtt-broker
  namespace: {{ .Release.Namespace | default "apps" }}
spec:
  selector:
    app: mqtt-broker
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
    - name: websockets
      port: 9002
      targetPort: websockets
