apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: redis-custom-config
  namespace: apps
data:
  redis-additional.conf: |
    maxmemory 384mb
    maxmemory-policy allkeys-lru

---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: redis
  namespace: apps
spec:
  clusterSize: 1              # 1 Master (Lab Mode)
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.12
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  redisConfig:
    additionalRedisConfig: redis-custom-config
  redisExporter:
    enabled: true             # Gotowe metryki do Grafany bez dodatkowego konfigurowania
    image: "oliver006/redis_exporter:v1.67.0"
    imagePullPolicy: IfNotPresent
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi