apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisReplication
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: redis
  namespace: apps
spec:
  clusterSize: 3              # 1 Master + 2 Repliki (Zero Downtime)
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.12
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  redisConfig:
    additionalRedisConfig: |
      maxmemory 384mb
      maxmemory-policy allkeys-lru
  redisExporter:
    enabled: true             # Gotowe metryki do Grafany bez dodatkowego konfigurowania
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi