apiVersion: v1
kind: Secret
metadata:
  name: backend-runtime-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.SPRING_DATASOURCE_USERNAME | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.SPRING_DATASOURCE_PASSWORD | quote }}
  CLICKHOUSE_USER: {{ .Values.secrets.CLICKHOUSE_USER | default "default" | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.secrets.CLICKHOUSE_PASSWORD | default "default_password" | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.MINIO_ACCESS_KEY | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.MINIO_SECRET_KEY | quote }}
  NEO4J_USER: {{ .Values.secrets.NEO4J_USER | quote }}
  NEO4J_PASSWORD: {{ .Values.secrets.NEO4J_PASSWORD | quote }}
  VAULT_TOKEN: {{ .Values.config.VAULT_TOKEN | quote }}
  SENTRY_DSN: {{ .Values.secrets.SENTRY_DSN | quote }}

