{{- if .Values.istio.enabled }}
{{- $services := list "userservice" "userservice-edge" "socialgraph-service" "socialgraph-edge" "search-service" "video-abr-service" "apollo-router" "tusd" "feedservice" "feed-edge-service" "chat-service" "chat-edge-service" "mqtt-broker" "linkguard-service" "linkguard-worker" "inference-service" "notificationservice" "analytics-service" "recommend-service" "groups-service" "marketplace-service" "marketplace-edge-service" }}
{{- range $services }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ . }}-sa
  namespace: {{ $.Release.Namespace | default "default" }}
---
{{- end }}
{{- end }}
