apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: socialgraph-service
  labels:
    app: socialgraph-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: socialgraph-service
  template:
    metadata:
      labels:
        app: socialgraph-service

      annotations:

        prometheus.io/scrape: "true"

        prometheus.io/path: "/actuator/prometheus"

        prometheus.io/port: "8082"
    spec:
      {{- if .Values.istio.enabled }}

      serviceAccountName: socialgraph-service-sa

      {{- end }}

      containers:
        - name: socialgraph-service
          image: "{{ .Values.images.socialgraphService.repository }}:{{ .Values.images.socialgraphService.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8082
            - name: grpc
              containerPort: 9091
          env:
            - name: NEO4J_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-runtime-config
                  key: NEO4J_URI
            - name: NEO4J_USER
              valueFrom:
                secretKeyRef:
                  name: backend-runtime-secrets
                  key: NEO4J_USER
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-runtime-secrets
                  key: NEO4J_PASSWORD
            - name: VAULT_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-runtime-config
                  key: VAULT_URI
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-runtime-secrets
                  key: VAULT_TOKEN
            - name: JAVA_TOOL_OPTIONS
              value: -Xms128m -Xmx256m

          readinessProbe:
            grpc:
              port: 9091
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            grpc:
              port: 9091
            initialDelaySeconds: 40
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: socialgraph-service
spec:
  selector:
    app: socialgraph-service
  ports:
    - name: http
      port: 8082
      targetPort: http
    - name: grpc
      port: 9091
      targetPort: grpc
