# router.yaml
supergraph:
  listen: 0.0.0.0:4000
  path: /graphql
  introspection: true

cors:
  origins:
    - https://lab-bm.com
    - https://api.lab-bm.com
    - http://localhost:3000
    - http://localhost:5173
  allow_any_origin: true

sandbox:
  enabled: true

homepage:
  enabled: false

include_subgraph_errors:
  all: true

health_check:
  listen: 0.0.0.0:8088
  path: /health

headers:
  all:
    request:
      - propagate:
          matching: "(?i)^(authorization|x-.*)$"

rhai:
  scripts: "/dist/config"
  main: "main.rhai"

