apiVersion: v2
name: facebook-clone-backend
description: Helm Chart dla mikroserwisów backendu i Apollo Router
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: operator
    version: "5.0.14"
    repository: "https://operator.min.io/"
    alias: minio-operator
  - name: clickhouse-operator-helm
    version: "0.27.3"
    repository: "oci://ghcr.io/clickhouse"
    alias: clickhouse-operator
